from __future__ import annotations
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
from datetime import datetime, timezone
import json

EXCLUDE_NAMES = {'.git', '__pycache__', '.venv', 'venv', 'dist', 'build', '.pytest_cache'}
EXCLUDE_SUFFIXES = {'.pyc', '.pyo'}

def build_zip(source: Path, output: Path, product: str = 'Angel Platform Project') -> Path:
    source = source.resolve(); output = output.resolve()
    if not source.exists() or not source.is_dir():
        raise ValueError(f'Source directory does not exist: {source}')
    output.parent.mkdir(parents=True, exist_ok=True)
    manifest = {
        'product': product,
        'version': '1.1.0-finish-day',
        'created_utc': datetime.now(timezone.utc).isoformat(),
        'source_name': source.name,
        'files': 0,
    }
    with ZipFile(output, 'w', ZIP_DEFLATED) as archive:
        for path in sorted(source.rglob('*')):
            if not path.is_file() or path.resolve() == output:
                continue
            relative = path.relative_to(source)
            if any(part in EXCLUDE_NAMES for part in relative.parts) or path.suffix in EXCLUDE_SUFFIXES:
                continue
            archive.write(path, relative.as_posix())
            manifest['files'] += 1
        archive.writestr('BUILD_MANIFEST.json', json.dumps(manifest, indent=2))
    return output

def create_project_scaffold(destination: Path, project_name: str, description: str) -> Path:
    safe = ''.join(ch for ch in project_name if ch.isalnum() or ch in ('-', '_', ' ')).strip() or 'angel-generated-project'
    root = destination / safe.replace(' ', '-')
    root.mkdir(parents=True, exist_ok=True)
    (root / 'README.md').write_text(f'# {safe}\n\n{description}\n\nGenerated by Angel AI Build Engine.\n', encoding='utf-8')
    (root / 'src').mkdir(exist_ok=True)
    (root / 'src' / 'main.py').write_text('def main():\n    print("Generated project is ready for customization.")\n\nif __name__ == "__main__":\n    main()\n', encoding='utf-8')
    (root / 'tests').mkdir(exist_ok=True)
    (root / 'tests' / 'test_smoke.py').write_text('def test_generated_project_smoke():\n    assert True\n', encoding='utf-8')
    return root
